import * as React from 'react';
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';

import './global.css';
import Aside from '@/components/Aside';
import Header from '@/components/Header';
import Main from '@/components/Main';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isFullScreen = true;

  return (
    <AntdRegistry>
      <html lang='en'>
        {isFullScreen ? (
          <body className='flex'>
            <Main />
          </body>
        ) : (
          <body className='flex'>
            <Aside />
            <div className='flex flex-shrink flex-grow flex-col'>
              <Header />
              <Main />
            </div>
          </body>
        )}
      </html>
    </AntdRegistry>
  );
}
